In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../Data/googleform.csv")

In [3]:
df.head()

,Timestamp,Username,Name,Height (in cm),Weight (in kg),Age,Gender,City,Locality,Languages (Separated by space),College/School,Working Profession,Have you gone trekking before?,Preference of Trek Days (Select all that apply),Number of Previous treks?,"If yes, List the treks separated by underscore (_)",Preference of difficulty of trek,Food Preferences,Unnamed: 18
0,2022/09/26 6:17:41 PM GMT+5:30,sourabhbajaj34@gmail.com,Sourabh Bajaj,185,70,20,Male,PUNE CITY,Pune,Hindi,MITWPU,Student,Yes,Saturday,3,NaN,Intermediate,Veg,sourabhbajaj34@gmail.com
1,2022/09/26 6:19:23 PM GMT+5:30,pawarnakshatra57@gmail.com,Nakshatra Pawar,162,69,20,Female,Chandrapur,NaN,"Hindi , marathi",MITWPU,Student,No,Saturday;Sunday,0,NaN,Intermediate,Veg,pawarnakshatra57@gmail.com
2,2022/09/26 6:20:13 PM GMT+5:30,varunrpoojari50@gmail.com,Varun Poojari,158,60,19,Male,Pune,Camp,English,MIT-WPU,Student,Yes,Saturday;Sunday,2,Sinhagadtrek_Harkidoon,Intermediate,Veg,varunrpoojari50@gmail.com
3,2022/09/26 6:20:40 PM GMT+5:30,arduinofan1atmega@gmail.com,Advait Shekhar Kulkarni,180,60,20,Male,Pune,Erandwane,English & Marathi,MIT WPU,Student,Yes,Friday;Saturday;Sunday,10+,Torna_tikona_sinhagad_katrajToSinhagad_salher_...,Hard,Veg,arduinofan1atmega@gmail.com
4,2022/09/26 6:23:16 PM GMT+5:30,chaitanya412001@gmail.com,Chaitanya Sarjerao Gomkar,172,100,21,Male,Pune,Nagpur,Marathi,MIT-WPU,"UG, Chemical Engineering",Yes,Sunday,2,ARAI Hills_Mathoba Hills_Raigad_Rajgad,Intermediate,Veg,chaitanya412001@gmail.com

In [4]:
# split Number of previous treks by - and keep the first value
df['Number of Previous treks?'] = df['Number of Previous treks?'].str.split('-').str[0]
# remove all non digit characters from Number of Previous treks? and then split the string into a list and keep only the first element
df['Number of Previous treks?'] = df['Number of Previous treks?'].str.replace(r'\D', '').str.split().str[0]
# remove all non digit characters from Height (in cm) , Weight (in kg)	and Age
df['Height (in cm)'] = df['Height (in cm)'].str.replace(r'\D', '')
df['Weight (in kg)'] = df['Weight (in kg)'].str.replace(r'\D', '')
# if Age contains - then split the string into a list and keep only the first element
df['Age'] = df['Age'].str.split('-').str[0]
df['Age'] = df['Age'].str.replace(r'\D', '')
# keep only first 2 characters of age
df['Age'] = df['Age'].str[:2]

/tmp/ipykernel_5579/870365555.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Number of Previous treks?'] = df['Number of Previous treks?'].str.replace(r'\D', '').str.split().str[0]
/tmp/ipykernel_5579/870365555.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Height (in cm)'] = df['Height (in cm)'].str.replace(r'\D', '')
/tmp/ipykernel_5579/870365555.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Weight (in kg)'] = df['Weight (in kg)'].str.replace(r'\D', '')
/tmp/ipykernel_5579/870365555.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Age'] = df['Age'].str.replace(r'\D', '')

In [5]:
# split Preference of Trek Days (Select all that apply)	 into a list SEPERATED BY ; value should be a list
df['Preference of Trek Days (Select all that apply)'] = df['Preference of Trek Days (Select all that apply)']
# replace all non a-z characters with space in Languages (Separated by space)	
df['Languages (Separated by space)'] = df['Languages (Separated by space)'].str.replace(r'[^a-zA-Z]', ' ')


# REMOVE Unnamed: 18 column
# remove Username column
# remove Name column
# remove Timestamp column
df = df.drop(['Username'], axis=1)
df = df.drop(['Unnamed: 18'], axis=1)
df = df.drop(['Name'], axis=1)
df = df.drop(['Timestamp'], axis=1)

/tmp/ipykernel_5579/3190897819.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Languages (Separated by space)'] = df['Languages (Separated by space)'].str.replace(r'[^a-zA-Z]', ' ')

In [6]:
df

,Height (in cm),Weight (in kg),Age,Gender,City,Locality,Languages (Separated by space),College/School,Working Profession,Have you gone trekking before?,Preference of Trek Days (Select all that apply),Number of Previous treks?,"If yes, List the treks separated by underscore (_)",Preference of difficulty of trek,Food Preferences
0,185,70,20,Male,PUNE CITY,Pune,Hindi,MITWPU,Student,Yes,Saturday,3,NaN,Intermediate,Veg
1,162,69,20,Female,Chandrapur,NaN,Hindi marathi,MITWPU,Student,No,Saturday;Sunday,0,NaN,Intermediate,Veg
2,158,60,19,Male,Pune,Camp,English,MIT-WPU,Student,Yes,Saturday;Sunday,2,Sinhagadtrek_Harkidoon,Intermediate,Veg
3,180,60,20,Male,Pune,Erandwane,English Marathi,MIT WPU,Student,Yes,Friday;Saturday;Sunday,10,Torna_tikona_sinhagad_katrajToSinhagad_salher_...,Hard,Veg
4,172,100,21,Male,Pune,Nagpur,Marathi,MIT-WPU,"UG, Chemical Engineering",Yes,Sunday,2,ARAI Hills_Mathoba Hills_Raigad_Rajgad,Intermediate,Veg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,18,90,47,Male,Mumbai,Chembur,English,K j Somaiya,IT,Yes,Saturday;Sunday,10,"Nani GHAt, Karnala",Intermediate,Non-Veg
101,155,62,49,Female,Pune,PCMC,Marathi Hindi English,BVMC and BJMC Pune,Doctor,Yes,Saturday;Sunday,5,"Dhak bhairi, Purandar, Lohgad fort, Sinhgad fort",Easy,Veg
102,16154,58,47,Female,Mumbai,Chembur,English Marathi Hindi,K J Somaiya,Banker,No,Saturday,0,NaN,Intermediate,Veg
103,168,64,20,Male,Punr,Kothrud,Hindi Marathi English,Mit wpu,Student,Yes,Friday;Saturday;Sunday,1,Sinhgad fort,Hard,Non-Veg
104,167,79,47,Female,Pune,Wakad,English Marathi Hindi,Nehru English School Nanded,Doctor,Yes,Sunday,6,NaN,Intermediate,Veg

In [7]:
# turn all string columns into lower case
df = df.apply(lambda x: x.astype(str).str.lower())

In [8]:
df

,Height (in cm),Weight (in kg),Age,Gender,City,Locality,Languages (Separated by space),College/School,Working Profession,Have you gone trekking before?,Preference of Trek Days (Select all that apply),Number of Previous treks?,"If yes, List the treks separated by underscore (_)",Preference of difficulty of trek,Food Preferences
0,185,70,20,male,pune city,pune,hindi,mitwpu,student,yes,saturday,3,nan,intermediate,veg
1,162,69,20,female,chandrapur,nan,hindi marathi,mitwpu,student,no,saturday;sunday,0,nan,intermediate,veg
2,158,60,19,male,pune,camp,english,mit-wpu,student,yes,saturday;sunday,2,sinhagadtrek_harkidoon,intermediate,veg
3,180,60,20,male,pune,erandwane,english marathi,mit wpu,student,yes,friday;saturday;sunday,10,torna_tikona_sinhagad_katrajtosinhagad_salher_...,hard,veg
4,172,100,21,male,pune,nagpur,marathi,mit-wpu,"ug, chemical engineering",yes,sunday,2,arai hills_mathoba hills_raigad_rajgad,intermediate,veg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,18,90,47,male,mumbai,chembur,english,k j somaiya,it,yes,saturday;sunday,10,"nani ghat, karnala",intermediate,non-veg
101,155,62,49,female,pune,pcmc,marathi hindi english,bvmc and bjmc pune,doctor,yes,saturday;sunday,5,"dhak bhairi, purandar, lohgad fort, sinhgad fort",easy,veg
102,16154,58,47,female,mumbai,chembur,english marathi hindi,k j somaiya,banker,no,saturday,0,nan,intermediate,veg
103,168,64,20,male,punr,kothrud,hindi marathi english,mit wpu,student,yes,friday;saturday;sunday,1,sinhgad fort,hard,non-veg
104,167,79,47,female,pune,wakad,english marathi hindi,nehru english school nanded,doctor,yes,sunday,6,nan,intermediate,veg

In [9]:
# make sure height is not more than 3 digits
df['Height (in cm)'] = df['Height (in cm)'].str[:3]
# parse height to int
df['Height (in cm)'] = df['Height (in cm)'].astype(int)
# make sure weight is not more than 500kg
# parse the string to int and then convert it back to string
df['Weight (in kg)'] = df['Weight (in kg)'].apply(lambda x: str(int(x) if int(x) < 500 else x[:2]))
# make sure age is not more than 99
df['Age'] = df['Age'].apply(lambda x: str(int(x) if int(x) < 99 else 99))
# # number of treks should be 2 digits or less
# # if number of digits is more than 4, then keep only the first 2 digits
# df['Number of previous treks'] = df['Number of previous treks'].apply(lambda x: str((x) if len(x) == 4 else x[:2]))
# # if number of digits is 3, then keep only the last 2 digits
# df['Number of previous treks'] = df['Number of previous treks'].apply(lambda x: str((x) if len(x) == 3 else x[-2:]))

In [10]:
df.to_json('../Data/googleform_cleaned.json', orient='records')

In [11]:
df.to_csv('../Data/googleform_cleaned.csv', index=False)